FROM ubuntu:16.04

#ssh
RUN apt-get update && apt-get install -y openssh-server

RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]

#account
RUN adduser hadoop
RUN echo 'hadoop:m40931gf' | chpasswd

#java
RUN apt-get -y install software-properties-common
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    add-apt-repository -y ppa:webupd8team/java && \
    apt-get update && \
    apt-get install -y oracle-java8-installer && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/oracle-jdk8-installer

#hadoop
RUN mkdir -p /root/soft/apache/hadoop
WORKDIR /root/soft/apache/hadoop

#env
ENV JAVA_HOME=/usr/lib/jvm/java-8-oracle 
ENV	HADOOP_HOME=/root/soft/apache/hadoop/hadoop-1.2.1
ENV	HADOOP_CONFIG_HOME=$HADOOP_HOME/conf
ENV	PATH=$PATH:$HADOOP_HOME/bin 
ENV	PATH=$PATH:$HADOOP_HOME/sbin 













	


